name: Official Build

on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - rel/*
    tags:
      - v*.*.*

env:
  ArtifactsDirectoryName: 'artifacts'
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any CPU'
  ContinuousIntegrationBuild: 'true'
  DotNet10Version: '10.x'
  IsOfficialBuild: 'true'

jobs:
  build:
    runs-on: windows-latest
    environment: Production

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install .NET ${{ env.DotNet10Version }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          ${{ env.DotNet10Version }}

    - name: Build Solution
      run: dotnet build "/Property:Platform=${{ env.BuildPlatform }};Configuration=${{ env.BuildConfiguration }}" "/BinaryLogger:${{ env.ArtifactsDirectoryName }}\build.binlog"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v5
      if: success()
      with:
        name: ${{ env.ArtifactsDirectoryName }}
        path: ${{ env.ArtifactsDirectoryName }}

    - name: Push Packages
      run: dotnet nuget push --skip-duplicate --api-key ${{ secrets.NuGetApiKey }} ${{ env.ArtifactsDirectoryName }}\**\*.nupkg
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
